/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
export const domain={
 code:'TESTAGENT',systemName:'知华软件测试智能体',englishName:'AI TEST ORCHESTRATION',theme:{primary:'#604c8d',dark:'#29263d',accent:'#d08a45'},
 workspace:'研发效能中心 / 质量平台组',fieldWorkspace:'订单产品线 / 测试小队',period:'2026-08-17 · 发布 R26.8.3',liveText:'流水线于 14:18 更新',fieldContextLabel:'当前发布',fieldContext:'R26.8.3 · 冻结前 2 天',fieldUser:'周屿',fieldRole:'测试工程师',adminUser:'顾清',adminRole:'测试平台主管',
 adminTitle:'AI 测试运营中心',adminBreadcrumb:'研发效能 / 智能测试',adminSubtitle:'根据代码变更、事故历史和关键链路自动组合测试计划，并用发布门禁保留人工责任。',exportAction:'导出质量周报',createAction:'新建测试计划',chartTitle:'核心服务覆盖率',chartSubtitle:'自动化覆盖率 / 发布目标',chartLabels:['R26.7.1','R26.7.2','R26.7.3','R26.7.4','R26.8.0','R26.8.1','R26.8.2','R26.8.3','目标'],loadTitle:'流水线资源负载',loadSubtitle:'执行器占用与排队情况',recordsTitle:'发布测试计划',recordsSubtitle:'按变更风险、关键链路和缺陷历史排序',issueTitle:'质量门禁提醒',issueSubtitle:'覆盖缺口、不稳定用例和生产事故防回归',
 recordName:'测试计划',itemName:'服务 / 版本',unitName:'负责团队',batchName:'测试套件',planName:'计划用例',doneName:'已执行',exceptionName:'失败',unitLabel:'例',listBreadcrumb:'智能测试 / 发布计划',listSubtitle:'从变更影响到回归执行、缺陷阻断和发布证据形成完整闭环。',listSummary:[['本周发布','18'],['自动化用例','1,286'],['高风险','6',true],['已通过','11']],tabs:['全部','待设计','执行中','待复核','已发布'],
 fieldBreadcrumb:'测试工作台 / 订单线',fieldTitle:'智能回归工作台',fieldSubtitle:'我的计划 6 个 · 正在执行 2 个 · 待复核 3 个',fieldSecondary:'查看变更影响',reportAction:'提交执行结果',fieldNoticeTitle:'测试环境运行稳定',fieldNotice:'关键链路覆盖率 92.4%',steps:['读取变更','识别风险','生成用例','并行执行','发布裁决'],documentAction:'查看测试资产',printAction:'导出测试报告',resourceCardTitle:'测试执行资源',resourceValueLabel:'在线执行器',resourceHealthLabel:'环境可用率',quickSubtitle:'测试工作入口',quickActions:[['执行回归','/shopfloor/report','用例、环境与失败证据'],['测试资产','/shopfloor/material','用例、数据和接口契约'],['环境状态','/shopfloor/resources','执行器、数据库和依赖'],['阻断升级','/shopfloor/andon','P0/P1 缺陷与事故复现']],
 reportDefaults:[24,1],reportTitle:'测试执行反馈',reportSubtitle:'记录通过、失败、阻塞原因和关联变更。',reportSuccess:'测试结果已提交',reportPlaceholder:'填写失败现象、日志位置、复现步骤或环境说明',reportFootnote:'P0/P1 失败会自动进入发布负责人复核',ruleTitle:'发布质量门禁',ruleSubtitle:'TEST-GATE · R26.8',rules:[['关键链路','必须全部通过'],['数据库变更','必须验证回滚'],['不稳定用例','隔离并复跑'],['生产事故','必须防回归',true]],fieldTotals:[['6','我的计划'],['2','正在执行'],['48','在线执行器'],['92.4%','关键链路覆盖']],
 adminMenus:[['/admin','home','测试运营中心'],['/admin/work-orders','order','发布计划'],['/admin/samples','box','测试资产'],['/admin/schedule','calendar','流水线排期'],['/admin/methods','process','策略模板'],['/admin/reviews','quality','发布门禁'],['/admin/resources','machine','测试环境'],['/admin/report','chart','质量分析']],fieldMenus:[['/shopfloor','home','回归工作台'],['/shopfloor/report','report','执行反馈'],['/shopfloor/tasks','order','我的计划'],['/shopfloor/material','box','测试资产'],['/shopfloor/resources','machine','环境状态'],['/shopfloor/andon','risk','缺陷升级',3]],moduleTitles:{tasks:['我的测试计划','查看变更、套件和执行状态'],material:['测试资产库','统一维护用例、数据和接口契约'],resources:['测试环境中心','管理执行器、依赖和健康度'],andon:['质量阻断升级','提交 P0/P1 缺陷和复现证据'],samples:['测试资产','管理关键链路与测试数据'],schedule:['流水线排期','协调执行窗口和并发资源'],methods:['策略模板','维护风险权重和回归组合'],reviews:['发布门禁','记录通过、阻断和例外审批'],report:['质量分析','分析覆盖率、缺陷和执行效率']},
 tagline:'让每次变更，都有恰到好处的测试证据',storyTitle:'识别变更风险，<br/>自动组合回归计划',storyText:'把代码变更、关键链路、覆盖率和事故历史放进同一套发布判断。',pattern:[2,4,6,9,12,15,18,21,24,27,30,34],loginStats:[['1,286','自动化用例'],['92.4%','关键链路覆盖'],['6','高风险发布']],loginTitle:'AI 测试运营中心',adminDemo:'计划 / 门禁 / 分析',fieldDemo:'执行 / 缺陷 / 证据'}
export const records=[{no:'TP-260817-042',name:'订单服务 R26.8.3',code:'ORDER-SVC',unit:'交易研发组',group:'订单产品线',plan:186,done:142,exception:5,due:'今天 18:00',batch:'冒烟+核心回归',status:'执行中',progress:76,priority:'P0'},{no:'TP-260817-039',name:'会员中心 R26.8.2',code:'MEMBER-SVC',unit:'客户平台组',group:'会员产品线',plan:96,done:96,exception:0,due:'今天 16:00',batch:'接口+权限',status:'待复核',progress:100,priority:'P1'},{no:'TP-260817-036',name:'结算服务热修复',code:'SETTLE-SVC',unit:'财务科技组',group:'结算产品线',plan:128,done:54,exception:3,due:'今天 20:00',batch:'事故防回归',status:'执行中',progress:42,priority:'P0'},{no:'TP-260816-031',name:'商品中心 R26.8.1',code:'PIM-SVC',unit:'商品研发组',group:'商品产品线',plan:82,done:82,exception:1,due:'08-16',batch:'全量回归',status:'已通过',progress:100,priority:'P2'},{no:'TP-260815-024',name:'营销规则引擎',code:'PROMO-SVC',unit:'营销研发组',group:'营销产品线',plan:104,done:104,exception:0,due:'08-15',batch:'规则组合',status:'已发布',progress:100,priority:'P1'}]
export const resources=[{code:'RUNNER-01',name:'容器测试执行池',unit:'质量平台组',status:'运行中',health:96,value:'48',valueUnit:'节点',note:'当前并发 36，排队 12'},{code:'ENV-ORDER',name:'订单集成测试环境',unit:'交易研发组',status:'运行中',health:98,value:'v26.8',valueUnit:'',note:'数据已于 13:40 重置'},{code:'DEVICE-02',name:'移动设备云',unit:'终端测试组',status:'复核中',health:91,value:'32',valueUnit:'设备',note:'2 台 Android 设备离线'}]
export const reviews=[{no:'GT-260817-032',title:'订单服务 R26.8.3',type:'发布门禁',detail:'5 个失败 · 顾清',result:'待确认'},{no:'GT-260817-027',title:'会员中心 R26.8.2',type:'覆盖确认',detail:'关键链路 100% · 周屿',result:'通过'},{no:'GT-260817-018',title:'结算热修复',type:'事故防回归',detail:'退款链路仍有 1 个失败',result:'异常'}]
export const adminMetrics=[['本周发布','18 个','6 个高风险变更','blue'],['自动化覆盖率','86.7%','较上月提升 3.2%','green'],['运行中用例','428 例','36 个执行器忙碌','orange'],['门禁阻断','3 个','均关联 P0/P1 缺陷','red']]
export const fieldMetrics=[['我的计划','6','2 个执行中','blue'],['今日通过','248 例','成功率 96.1%','green'],['失败待查','9 例','3 例阻断发布','orange'],['环境可用率','97.2%','2 个依赖告警','slate']]
export const chartActual=[68,72,75,78,80,82,84,87,89],chartTarget=[75,76,78,80,82,84,86,88,90]
export const loads=[['容器执行池',75,'36 / 48 节点'],['移动设备云',63,'20 / 32 设备'],['接口虚拟化',48,'QPS 1,260'],['性能测试池',42,'10 / 24 节点']]
export const issues=[['门禁','订单支付链路存在 2 个 P0 失败','已阻断 R26.8.3 发布','待修复'],['波动','会员权限用例近三次结果不一致','已隔离并安排连续复跑','处理中'],['环境','结算环境消息队列延迟升高','已切换备用测试集群','已恢复']].map(x=>({type:x[0],title:x[1],detail:x[2],status:x[3]}))
