/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.testagent.controller;import cn.zhuatech.testagent.common.ApiResponse;import cn.zhuatech.testagent.service.TestReleaseCertificationService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                */
@RestController @RequestMapping("/api/enterprise/testagent")public class TestReleaseCertificationController{private final TestReleaseCertificationService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                  */
public TestReleaseCertificationController(TestReleaseCertificationService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@PostMapping("/test-release-certification")public ApiResponse<TestReleaseCertificationService.Assessment>assess(@Valid @RequestBody TestReleaseCertificationService.Request request){return ApiResponse.ok(service.assess(request));}}
