/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.testagent.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                  */
class TestReleaseCertificationServiceTest{private final TestReleaseCertificationService s=new TestReleaseCertificationService();/**
                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                  */
@Test void certifiesTestedRelease(){var r=s.assess(new TestReleaseCertificationService.Request("R1",true,true,true,true,true,true,0,true,true,true,true));assertThat(r.decision()).isEqualTo(TestReleaseCertificationService.Decision.CERTIFY);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@Test void conditionallyCertifiesOperationalGaps(){var r=s.assess(new TestReleaseCertificationService.Request("R2",true,true,true,true,true,true,0,true,false,false,true));assertThat(r.actions()).hasSize(2);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
@Test void blocksUntestedRelease(){var r=s.assess(new TestReleaseCertificationService.Request("R3",false,false,false,false,false,false,3,false,true,true,false));assertThat(r.blockers()).hasSize(9);}}
